import test from 'node:test';import assert from 'node:assert/strict';
import {Game,createLevel,overlap,WORLD} from '../src/engine.js';
const step=(g,n,input={})=>{for(let i=0;i<n;i++)g.step(1/120,input);};
test('spawn settles and W jumps once per keypress',()=>{const g=new Game();step(g,20);assert.equal(g.player.ground,true);step(g,30,{jump:true});assert.ok(g.player.y<2600);step(g,180,{jump:true});assert.equal(g.player.y,2712);});
test('crouch passes low tunnel, cannot stand inside ceiling',()=>{const g=new Game();g.player.x=280;step(g,60,{right:true});assert.ok(g.player.x<=284.01);step(g,90,{right:true,crouch:true});assert.ok(g.player.x>330);step(g,20);assert.equal(g.player.h,28);assert.ok(!g.level.platforms.some(p=>overlap(g.player,p)));step(g,160,{right:true,crouch:true});step(g,10);assert.equal(g.player.h,48);});
test('chest unlocks sword and bow; switching works',()=>{const g=new Game();g.player.x=550;step(g,1,{use:true});assert.equal(g.player.weapon,'sword');assert.equal(g.level.chests[0].open,true);step(g,1);g.player.x=g.level.chests[1].x;g.player.y=g.level.chests[1].y-20;step(g,1,{use:true});assert.equal(g.player.bow,true);step(g,1,{slot:1});assert.equal(g.player.weapon,'fist');step(g,1,{slot:2});assert.equal(g.player.weapon,'sword');step(g,1,{slot:3});assert.equal(g.player.weapon,'bow');step(g,1,{slot:1});assert.equal(g.player.weapon,'fist');});
test('sword damage, knockback, invulnerability and attack cooldown',()=>{const g=new Game();const p=g.player,b=g.level.bots[0];Object.assign(b,{x:p.x+45,y:p.y});p.weapon='sword';g.attack(p);assert.equal(b.hp,66);assert.ok(b.kb>0);g.attack(p);assert.equal(b.hp,66);g.damage(b,20,1);assert.equal(b.hp,66);});
test('bow arrow hits opponent and is consumed',()=>{const g=new Game();const p=g.player,b=g.level.bots[0];Object.assign(p,{x:550,weapon:'bow'});Object.assign(b,{x:650,y:p.y,home:0});g.attack(p);step(g,25);assert.ok(b.hp<100);assert.equal(g.projectiles.length,0);});
test('death and falling respawn at start with full health',()=>{const g=new Game();g.player.y=WORLD.height+1;step(g,1);assert.equal(g.deaths,1);assert.equal(g.player.hp,100);assert.equal(g.player.x,175);g.player.hp=0;step(g,1);assert.equal(g.deaths,2);});
test('spikes hurt player; crown completes run',()=>{const g=new Game();const s=g.level.spikes[0];Object.assign(g.player,{x:s.x,y:s.y-20});step(g,1);assert.equal(g.player.hp,75);Object.assign(g.player,{x:g.level.goal.x,y:g.level.goal.y});step(g,1);assert.equal(g.won,true);const time=g.time;step(g,60);assert.equal(g.time,time);});
test('original approach routes have reachable platform gaps at full jump speed',()=>{for(let theme=0;theme<3;theme++){const level=createLevel(theme);const ps=level.platforms.slice(0,[22,20,21][theme]).filter(p=>!p.tunnel);for(let i=1;i<ps.length;i++){const a=ps[i-1],b=ps[i];const rise=a.y-b.y;assert.ok(rise<740**2/3000);const availableTime=(740+Math.sqrt(740**2-3000*rise))/1500;const gap=Math.max(b.x-a.x-a.w,a.x-b.x-b.w,0);assert.ok(gap+26<285*availableTime,`theme ${theme} step ${i}`);}}});

test('high first wall cannot be jumped over in any biome',()=>{for(let t=0;t<3;t++){const g=new Game(t);g.player.x=260;step(g,20);step(g,110,{jump:true,right:true});assert.ok(g.player.x<=284.01);assert.equal(g.deaths,0);step(g,230,{right:true,crouch:true});assert.ok(g.player.x>475);}});
test('locked weapons never replace fists',()=>{const g=new Game();g.selectWeapon(2);assert.equal(g.player.weapon,'fist');g.selectWeapon(3);assert.equal(g.player.weapon,'fist');});
test('biomes have different geometry, hazards and bot roles',()=>{const levels=[0,1,2].map(createLevel);assert.notDeepEqual(levels[0].platforms,levels[1].platforms);assert.notDeepEqual(levels[1].platforms,levels[2].platforms);assert.equal(levels[0].winds.length,0);assert.ok(levels[1].winds.length&&levels[1].icicles.length);assert.ok(levels[1].bots.some(b=>b.role==='archer'));assert.equal(levels[1].flames.length,0);assert.ok(levels[2].flames.length);assert.ok(levels[2].bots.every(b=>b.role==='guard'));});
test('ice preserves momentum longer than stone',()=>{const speeds=[];for(const t of [0,1]){const g=new Game(t);const plat=g.level.platforms[3];Object.assign(g.player,{x:plat.x+60,y:plat.y-48,vx:200,ground:true,onIce:!!plat.ice});g.move(g.player,.05,{});speeds.push(g.player.vx);}assert.ok(speeds[1]>speeds[0]*2);});
test('fire warns before damage, then cycles off',()=>{const g=new Game(2);g.level.bots=[];const f=g.level.flames[0];g.time=1.3-f.phase;Object.assign(g.player,{x:f.x,y:f.y+f.h-48});step(g,1);assert.ok(f.warning&&!f.active);assert.equal(g.player.hp,100);g.time=2.1-f.phase;step(g,1);assert.ok(f.active);assert.equal(g.player.hp,72);g.time=4.1-f.phase;step(g,1);assert.ok(!f.active&&!f.warning);});
test('icicles activate nearby, hurt and reset',()=>{const g=new Game(1);g.level.bots=[];const ice=g.level.icicles[0];ice.cooldown=0;Object.assign(g.player,{x:ice.x-13,y:ice.endY-28});step(g,1);assert.ok(ice.falling);step(g,90);assert.ok(g.player.hp<100);assert.equal(ice.falling,false);assert.equal(ice.y,ice.originY);});
test('ash lava respawns immediately on contact',()=>{const g=new Game(2);g.player.y=2940;step(g,1);assert.equal(g.deaths,1);assert.equal(g.player.hp,100);});
test('wind pushes airborne player in the indicated direction',()=>{const g=new Game(1);g.level.bots=[];const wind=g.level.winds[0];Object.assign(g.player,{x:wind.x+10,y:wind.y+50});step(g,1);assert.ok(g.player.vx>0);});

test('underside icicles damage on contact and respect immunity',()=>{const g=new Game(1);g.level.bots=[];const tip=g.level.underIce[0],plat=g.level.platforms[tip.platform];Object.assign(g.player,{x:plat.x+tip.offset,y:plat.y+plat.h+2});step(g,1);assert.equal(g.player.hp,85);step(g,1);assert.equal(g.player.hp,85);});
test('pickaxe chest unlocks fourth weapon',()=>{const g=new Game(1),c=g.level.chests.find(c=>c.weapon==='pickaxe');Object.assign(g.player,{x:c.x,y:c.y-24});step(g,1,{use:true});assert.ok(g.player.pickaxe);assert.equal(g.player.weapon,'pickaxe');g.selectWeapon(1);g.selectWeapon(4);assert.equal(g.player.weapon,'pickaxe');});
test('alternating pickaxe wall jumps traverse entire ice shaft',()=>{const g=new Game(1);g.level.bots=[];Object.assign(g.player,{x:800,y:272,pickaxe:true,weapon:'pickaxe'});let direction=-1,last=false,jumps=0;for(let i=0;i<1000&&g.player.y>-580;i++){const p=g.player;let jump=p.ground&&i%2===0;if(p.wallSide&&p.lastWall!==p.wallSide&&!last){jump=true;direction=-p.wallSide;jumps++;}g.step(1/120,{left:direction<0,right:direction>0,jump});last=jump;}assert.ok(g.player.y<-580);assert.ok(jumps>=4);assert.equal(g.deaths,0);});
test('wall jumping requires an equipped pickaxe and alternates sides',()=>{const g=new Game(1),p=g.player;Object.assign(p,{x:780,y:0,wallSide:-1,pickaxe:true,weapon:'fist'});g.move(p,1/120,{jump:true});assert.ok(p.vy>=0);Object.assign(p,{wallSide:-1,lastWall:-1,weapon:'pickaxe',vy:0,buffer:0});g.move(p,1/120,{jump:true});assert.ok(p.vy>=0);});
test('sand collapses, three guards lock exit, kills persist across respawn',()=>{const g=new Game(2),a=g.level.arena,s=g.level.platforms[a.sand];Object.assign(g.player,{x:s.x+60,y:s.y-48,inv:10});step(g,1);assert.equal(a.state,'crumbling');assert.ok(a.barrier.every(i=>!g.level.platforms[i].disabled));step(g,100);assert.equal(a.state,'active');assert.ok(g.level.platforms[a.sand].disabled);assert.ok(a.exits.every(i=>g.level.platforms[i].disabled));assert.equal(a.guards.length,3);g.damage(a.guards[0],100,1);g.respawn();assert.equal(a.guards[0].hp,0);assert.equal(g.player.y,452);for(const b of a.guards.slice(1))g.damage(b,100,1);step(g,1);assert.equal(a.state,'cleared');assert.ok(a.exits.every(i=>!g.level.platforms[i].disabled));step(g,800);assert.ok(a.guards.every(b=>b.hp===0));g.reset();assert.ok(g.level.arena.guards.every(b=>b.hp===60&&b.dormant));});
test('two tutorial snakes telegraph weak attacks and can be killed',()=>{const g=new Game(0);const snakes=g.level.bots.filter(b=>b.kind==='snake');assert.equal(snakes.length,2);assert.equal(g.level.trees.length,2);const b=snakes[0];g.level.bots=[b];Object.assign(g.player,{x:b.x-35,y:b.y+b.h-48,weapon:'sword'});step(g,30);assert.equal(g.player.hp,100);step(g,50);assert.equal(g.player.hp,92);g.player.x=b.x-40;g.player.y=b.y+b.h-48;g.player.dir=1;g.player.cooldown=0;g.attack(g.player);assert.equal(b.hp,0);});
test('new ice ledges and cleared arena stairway remain reachable',()=>{for(const theme of [1,2]){const l=createLevel(theme);const path=theme===1?l.platforms.slice(22):[l.platforms[l.arena.floor],...l.arena.exits.map(i=>l.platforms[i]),...l.platforms.slice(-2)];for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],rise=a.y-b.y;assert.ok(rise<182.5);const air=(740+Math.sqrt(740**2-3000*rise))/1500,gap=Math.max(b.x-a.x-a.w,a.x-b.x-b.w,0);assert.ok(gap+26<285*air);}}});
