// Original procedural ambience and effects. No downloads or external audio assets.
export function audioSettings(s={}){const level=(v,d)=>Number.isFinite(+v)?Math.max(0,Math.min(100,+v)):d;return {volume:level(s.volume??35,35),musicVolume:level(s.musicVolume??18,18)};}
export class GameAudio{
 constructor(settings={}){this.settings=audioSettings(settings);this.context=null;this.active=false;this.visible=true;this.note=0;this.next=0;this.recent=new Map();}
 unlock(){try{if(!this.context){const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)return;this.context=new C();this.fx=this.context.createGain();this.music=this.context.createGain();this.fx.connect(this.context.destination);this.music.connect(this.context.destination);this.configure(this.settings);this.timer=setInterval(()=>this.schedule(),200);}this.context.resume()?.catch(()=>{});}catch{}}
 configure(s){this.settings=audioSettings(s);if(this.context){const t=this.context.currentTime;this.fx.gain.setTargetAtTime(this.visible?this.settings.volume/100:0,t,.03);this.music.gain.setTargetAtTime(this.active&&this.visible?this.settings.musicVolume/100:0,t,.15);}}
 setActive(active){if(this.active===active)return;this.active=active;this.next=this.context?.currentTime||0;this.configure(this.settings);}
 setVisible(visible){this.visible=visible;this.configure(this.settings);}
 tone(freq,end,duration,level,type='sine',bus=this.fx,when=this.context?.currentTime){if(!this.context||!bus)return;const c=this.context,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,when);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),when+duration);g.gain.setValueAtTime(.0001,when);g.gain.linearRampToValueAtTime(level,when+.015);g.gain.exponentialRampToValueAtTime(.0001,when+duration);o.connect(g);g.connect(bus);o.onended=()=>{o.disconnect();g.disconnect();};o.start(when);o.stop(when+duration+.02);}
 hiss(level){const c=this.context,b=c.createBuffer(1,Math.ceil(c.sampleRate*.35),c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=b;f.type='highpass';f.frequency.value=2200;g.gain.value=.12*level;n.connect(f);f.connect(g);g.connect(this.fx);n.onended=()=>{n.disconnect();f.disconnect();g.disconnect();};n.start();}
 play(type,strength=1){const c=this.context;if(!c||c.state!=='running'||!this.visible||!this.settings.volume||strength<=0)return;const t=c.currentTime;if(t-(this.recent.get(type)??-99)<.07)return;this.recent.set(type,t);if(type==='snake'){this.hiss(strength);return;}const notes={jump:[330,495,.2],hit:[90,45,.2],attack:[180,90,.2],bow:[540,180,.18],chest:[660,990,.23],spawn:[520,780,.3],death:[100,40,.5],lose:[100,40,.5],win:[880,1320,.55],kill:[500,250,.2],guard:[120,65,.26],mobHit:[130,60,.18],bite:[240,75,.12],poison:[220,110,.25]};const n=notes[type];if(n)this.tone(...n,.11*strength,['hit','guard','mobHit'].includes(type)?'triangle':'sine');}
 schedule(){const c=this.context;if(!c||c.state!=='running'||!this.active||!this.visible||!this.settings.musicVolume)return;if(this.next<c.currentTime)this.next=c.currentTime+.04;const melody=[0,7,12,7,3,10,15,10,5,12,17,12,3,7,10,7];while(this.next<c.currentTime+.3){const i=this.note++%melody.length,base=146.83;this.tone(base*2**(melody[i]/12),base*2**(melody[i]/12),1.7,.09,'sine',this.music,this.next);if(i%4===0)this.tone(base/2,base/2,2.8,.07,'sine',this.music,this.next);this.next+=.75;}}
}
// Deduplicate the server's event window; never replay history after reconnecting.
export class ArenaAudio{
 constructor(audio){this.audio=audio;this.last=0;this.time=-1;this.initial=true;}
 reset(){this.initial=true;this.time=-1;this.last=0;}
 consume(g,listener){if(!g){this.reset();this.audio.setActive(false);return;}this.audio.setActive(g.phase==='running');const events=g.events||[];if(this.initial||g.time<this.time){this.last=events.at(-1)?.id||0;this.initial=false;}else for(const e of events)if(e.id>this.last){this.last=e.id;const distance=listener?Math.hypot(e.x-listener.x,e.y-listener.y):Infinity;const gain=e.type==='win'?1:Math.max(0,1-distance/700);this.audio.play(e.type,gain);}this.time=g.time;}
}
