import {normalizeBindings,toggleBinding,movementInput,LABELS} from './controls.js';
import {Game,THEMES,WORLD} from './engine.js';
import {Renderer} from './render.js';
const $=id=>document.getElementById(id),canvas=$('scene'),renderer=new Renderer(canvas);
let selected=0,state='menu',game,keys={},accumulator=0,last=0,toastUntil=0,audio;
let settings={volume:35,shake:true,particles:true};try{settings={...settings,...JSON.parse(localStorage.getItem('koth-settings')||'{}')};}catch{}
settings.bindings=normalizeBindings(settings.bindings);
$('volume').value=settings.volume;$('shake').checked=settings.shake;$('particles').checked=settings.particles;
function save(){settings={...settings,volume:+$('volume').value,shake:$('shake').checked,particles:$('particles').checked};try{localStorage.setItem('koth-settings',JSON.stringify(settings));}catch{}}
for(const id of ['volume','shake','particles'])$(id).addEventListener('input',save);
function updateHints(){for(const el of document.querySelectorAll('[data-key]'))el.textContent=LABELS[settings.bindings[el.dataset.key]];for(const el of document.querySelectorAll('[data-bind]')){const action=el.dataset.bind;el.textContent=LABELS[settings.bindings[action]]+' ⇄';el.setAttribute('aria-label',`Сменить клавишу: ${LABELS[settings.bindings[action]]}`);}}
for(const el of document.querySelectorAll('[data-bind]'))el.onclick=()=>{settings.bindings=toggleBinding(settings.bindings,el.dataset.bind);keys={};save();updateHints();};
updateHints();
function sound(type){if(!audio||!settings.volume)return;const oscillator=audio.createOscillator(),gain=audio.createGain();const freq={jump:330,hit:90,attack:180,chest:660,death:100,win:880,kill:500}[type];if(!freq)return;oscillator.type=type==='hit'?'triangle':'sine';oscillator.frequency.setValueAtTime(freq,audio.currentTime);oscillator.frequency.exponentialRampToValueAtTime(freq*(type==='jump'?1.5:.5),audio.currentTime+.16);gain.gain.setValueAtTime(settings.volume/100*.11,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+.21);}
function onEvent(type,text){sound(type);if(text){$('toast').textContent=text;toastUntil=performance.now()+2800;}if(type==='hit')renderer.shake=7;if(type==='win'){state='won';keys={};$('win-stats').textContent=`Время ${format(game.time)} · Падений: ${game.deaths} · Побеждено соперников: ${game.kills}`;$('win').showModal();}}
game=new Game(selected,onEvent);
function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
function start(){closeDialogs();try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}game=new Game(selected,onEvent);renderer.camera={x:0,y:2200};state='playing';keys={};accumulator=0;toastUntil=0;document.body.classList.add('playing');$('menu').hidden=true;$('hud').hidden=false;$('location').textContent=THEMES[selected].name.toUpperCase();$('toast').textContent='Путь наверх начинается здесь. Найди первый сундук →';toastUntil=performance.now()+4000;}
function menu(){closeDialogs();state='menu';keys={};game=new Game(selected,onEvent);document.body.classList.remove('playing');$('menu').hidden=false;$('hud').hidden=true;}
function pause(){if(state!=='playing')return;state='paused';keys={};$('pause-dialog').showModal();}
function resume(){closeDialogs();keys={};state='playing';accumulator=0;}
$('play').onclick=start;$('again').onclick=start;$('restart').onclick=start;$('resume').onclick=resume;$('pause').onclick=pause;$('back-menu').onclick=menu;$('win-menu').onclick=menu;document.querySelector('.brand').onclick=e=>{e.preventDefault();menu();};$('settings-top').onclick=()=>$('settings').showModal();$('controls-open').onclick=()=>$('controls').showModal();
$('pause-dialog').addEventListener('cancel',e=>{e.preventDefault();resume();});$('win').addEventListener('cancel',e=>{e.preventDefault();menu();});
for(const card of document.querySelectorAll('.world'))card.onclick=()=>{const old=selected;selected=+card.dataset.world;if(old!==selected)renderer.startTransition(old,selected,performance.now()/1000);document.querySelectorAll('.world').forEach(c=>{c.classList.toggle('active',c===card);c.setAttribute('aria-pressed',String(c===card));});game=new Game(selected,onEvent);};
for(let i=1;i<=4;i++)$('slot'+i).onclick=()=>game.selectWeapon(i);
window.addEventListener('keydown',e=>{if(e.code==='Escape'){if(state==='playing'){e.preventDefault();pause();}return;}if(state!=='playing')return;if(['KeyW','KeyA','KeyS','KeyD','KeyE','KeyH','KeyJ','Digit1','Digit2','Digit3','Digit4','ArrowLeft','ArrowRight','Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();keys[e.code]=true;});window.addEventListener('keyup',e=>delete keys[e.code]);canvas.addEventListener('pointerdown',e=>{if(e.button===0&&state==='playing')keys.Mouse=true;});window.addEventListener('pointerup',()=>delete keys.Mouse);window.addEventListener('blur',()=>{keys={};pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('resize',()=>renderer.resize());
function format(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
function hud(){const p=game.player;$('height-bar').style.width=Math.min(100,Math.max(0,(WORLD.startY-p.y-p.h)/(WORLD.startY-game.level.summit)*100))+'%';$('height').textContent=`${Math.max(0,Math.round((WORLD.startY-p.y-p.h)/10))} м / ${Math.round((WORLD.startY-game.level.summit)/10)} м`;$('timer').textContent=format(game.time);$('deaths').textContent=`ПАДЕНИЯ: ${game.deaths}`;for(const [i,w]of ['fist','sword','bow','pickaxe'].entries())$('slot'+(i+1)).classList.toggle('active',p.weapon===w);$('slot2').querySelector('span').textContent=p.sword?'Меч':'Найди меч';$('slot3').querySelector('span').textContent=p.bow?'Лук':'Найди лук';$('slot4').querySelector('span').textContent=p.pickaxe?'Кирка':'Найди кирку';$('toast').classList.toggle('visible',performance.now()<toastUntil);}
function loop(now){const dt=Math.min((now-last)/1000,.1);last=now;if(state==='playing'){accumulator+=dt;while(accumulator>=1/120){game.step(1/120,{...movementInput(keys,settings.bindings),attack:keys.KeyJ||keys.Mouse,slot:keys.Digit1?1:keys.Digit2?2:keys.Digit3?3:keys.Digit4?4:0});accumulator-=1/120;if(state!=='playing')break;}hud();}renderer.draw(game,now/1000,state==='menu',settings);requestAnimationFrame(loop);}
requestAnimationFrame(loop);
// Explicit test hook, enabled only for local automated verification.
if(new URLSearchParams(location.search).has('test'))window.__game={get game(){return game;},get state(){return state;},start,pause,resume,menu};
